@startuml
!include <cloudinsight/mongodb>
!include <cloudinsight/kafka>
!include <cloudinsight/redis>
!include <cloudinsight/haproxy>
!include <cloudinsight/sqlserver>
!include <cloudinsight/nodejs>
!include <cloudinsight/redis>
!include <logos/oracle>
!include <cloudinsight/sqlserver>
!include <cloudinsight/mongodb>
!include <logos/angular>
!include <logos/vue>
skinparam linetype ortho
title B2B - Strati Deployment

left to right direction

rectangle walmartChile as "Walmart Chile" {
    database atgDatabase as "\nATG\n<$oracle{scale=.4}>\n" #DarkGrey;line:white;line.bold;text:white
    database omsDatabase as "OMS <$sqlserver{scale=.4}>\n" #DarkGrey;line:white;line.bold;text:white
    rectangle checkout #DarkGrey;line:white;line.bold;text:white
    rectangle modelMaster as "Modelo Maestro ETL" #DarkGrey;line:white;line.bold;text:white
    rectangle OMS #DarkGrey;line:white;line.bold;text:white
    rectangle IMS #DarkGrey;line:white;line.bold;text:white
    rectangle promiseEngine as "Promise Engine" #DarkGrey;line:white;line.bold;text:white
    ' queue checkoutOrderPaid as "<$kafka{scale=.5}> checkout-order-paid-*" #black;line:white;line.bold;text:white
    rectangle OMS #DarkGrey;line:white;line.bold;text:white
    ' queue checkoutOrderReinjected as "<$kafka{scale=.5}> checkout-order-paid-reinjected-us-scus" #black;line:white;line.bold;text:white
    ' queue checkoutOrderRescheduledPublished as "<$kafka{scale=.5}> checkout_order_rescheduled-*" #black;line:white;line.bold;text:white
    rectangle mercurioChile as "Mercurio - B2B" {
        rectangle b2bService as "<$nodejs{scale=.5}> b2b-service" #RoyalBlue;line:white;line.bold;text:white
        rectangle mercurioOrdersBase as "<$nodejs{scale=.5}> mercurio-orders-base" #RoyalBlue;line:white;line.bold;text:white
        rectangle mercurioBffChile as "<$nodejs{scale=.5}> mercurio-bff" #RoyalBlue;line:white;line.bold;text:white
        rectangle mercurioJobsChile as "<$nodejs{scale=.5}> mercurio-jobs" #RoyalBlue;line:white;line.bold;text:white
        rectangle mercurioInventoryBase as "<$nodejs{scale=.5}> mercurio-inventory-base" #RoyalBlue;line:white;line.bold;text:white
        database redisCache as "\n<$redis{scale=.5}> Redis\n" #RoyalBlue;line:white;line.bold;text:white
        folder ftp #RoyalBlue;line:white;line.bold;text:white

        ' queue _mercurioUpdatePurchaseOrder as "<$kafka{scale=.5}> _mercurio-update-purchase-order-*" #black;line:white;line.bold;text:white
        ' queue _mercurioHatChanged as "<$kafka{scale=.5}> _mercurio-hat-changed-*" #black;line:white;line.bold;text:white
        ' queue _mercurioBrandChanged as "<$kafka{scale=.5}> _mercurio-brand-changed-*" #black;line:white;line.bold;text:white
        ' queue _mercurioVendorChanged as "<$kafka{scale=.5}> _mercurio-vendor-changed-*" #black;line:white;line.bold;text:white
        ' queue _mercurioSkuChanged as "<$kafka{scale=.5}> _mercurio-item-sku-changed-*" #black;line:white;line.bold;text:white
        ' queue _mercurioSkuRemoved as "<$kafka{scale=.5}> _mercurio-item-sku-removed-*" #black;line:white;line.bold;text:white
        ' queue _mercurioCeOrderPaid as "<$kafka{scale=.5}> _mercurio-ce-order-paid-*" #black;line:white;line.bold;text:white
        ' queue _mercurioUpdateOrdersOms as "<$kafka{scale=.5}> _mercurio-update-orders-oms-*" #black;line:white;line.bold;text:white
        ' queue _mercurioItemPublished as "<$kafka{scale=.5}> _mercurio-item-published-*" #black;line:white;line.bold;text:white
        ' queue _mercurioItemStockUpdated as "<$kafka{scale=.5}> _mercurio-item-stock-updated-*" #black;line:white;line.bold;text:white
        
    }
    queue eventChile as "<$kafka{scale=.5}> events" #black;line:white;line.bold;text:white
}

rectangle walmartGlobal as "Walmart Global" {
    rectangle mercurioGlobal as "Mercurio - B2B" {
        rectangle mercurioOrdersApi as "<$nodejs{scale=.5}> mercurio-orders-api" #RoyalBlue;line:white;line.bold;text:white
        rectangle mercurioAuthApi as "<$nodejs{scale=.5}> mercurio-auth-api" #RoyalBlue;line:white;line.bold;text:white
        rectangle mercurioJobsStrati as "<$nodejs{scale=.5}> mercurio-jobs" #RoyalBlue;line:white;line.bold;text:white
        rectangle mercurioInventoryApi as "<$nodejs{scale=.5}> mercurio-inventory-api" #RoyalBlue;line:white;line.bold;text:white
        database mercurioDataBase as "CosmosDB\n<$mongodb>" #RoyalBlue;line:white;line.bold;text:white
        rectangle public as "Public by Torbit" {
            rectangle b2bWeb as "b2b-web\n<$angular{scale=.6}>" #RoyalBlue;line:white;line.bold;text:white
            rectangle mercurioNow as "<$vue{scale=.4}>mercurio-now" #RoyalBlue;line:white;line.bold;text:white
        }

        rectangle publicProxy as "Public by ApiProxy" {
            rectangle mercurioClientApi as "<$nodejs{scale=.5}> mercurio-client-api" #RoyalBlue;line:white;line.bold;text:white
        }
        rectangle mercurioBff as "<$nodejs{scale=.5}> mercurio-bff" #RoyalBlue;line:white;line.bold;text:white
        ' queue _mercurioStockSync as "<$kafka{scale=.5}> _mercurio-stock-sync-*" #black;line:white;line.bold;text:white
    }
    rectangle retailLinkFalcon as "Falcon Retail Link 🔐" #DarkGrey;line:white;line.bold;text:white
    rectangle pingFed as "PingFed 🔐" #DarkGrey;line:white;line.bold;text:white
    queue eventStrati as "<$kafka{scale=.5}> events" #black;line:white;line.bold;text:white
    ' queue mercurioVendorLogisticUpdate as "<$kafka{scale=.5}> mercurio-vendor-logistic-update-*" #black;line:white;line.bold;text:white
    ' queue mercurioItemLeadtimeUpdated as "<$kafka{scale=.5}> mercurio-item-leadtime-updated-*" #black;line:white;line.bold;text:white

}

actor vendors as "Vendors Users" #Black;line:black;line.bold;text:black
actor colaborator as "Walmart Colaborator" #Blue;line:Blue;line.bold;text:Blue
rectangle vendorsSystems as "Vendors Systems" #Black;line:black;line.bold;text:white

queue replicator as "<$kafka{scale=.5}> Replicator" #black;line:white;line.bold;text:white {
}



b2bService -[#RoyalBlue]-> atgDatabase: "Get Sku, brand, vendor and rut"
b2bService <-[#RoyalBlue]-> redisCache: "Cache items information"
modelMaster -[#DarkGrey]-> ftp
b2bService -[#RoyalBlue]-> ftp
b2bService -[#RoyalBlue]-> omsDatabase 

' b2bService -[#RoyalBlue]--> _mercurioHatChanged
' b2bService -[#RoyalBlue]--> _mercurioBrandChanged
' b2bService -[#RoyalBlue]--> _mercurioVendorChanged
' b2bService -[#RoyalBlue]--> _mercurioSkuChanged
' b2bService -[#RoyalBlue]--> _mercurioSkuRemoved
' b2bService -[#RoyalBlue]--> _mercurioCeOrderPaid
' b2bService -[#RoyalBlue]--> _mercurioCeOrderPaid
' b2bService -[#RoyalBlue]--> _mercurioUpdateOrdersOms
' b2bService -[#RoyalBlue]--> _mercurioItemPublished
' b2bService -[#RoyalBlue]--> _mercurioUpdatePurchaseOrder

b2bService -[#RoyalBlue]--> eventChile

mercurioOrdersBase -[#RoyalBlue]--> omsDatabase
' mercurioOrdersBase -[#Black]--> _mercurioUpdateOrdersOms
mercurioOrdersBase -[#Black]--> eventChile
mercurioBffChile -[#RoyalBlue]-> mercurioOrdersBase

eventChile -[#Black]> replicator
eventStrati -[#Black]> replicator

' _mercurioHatChanged -[#Black]-> replicator
' _mercurioBrandChanged -[#Black]-> replicator
' _mercurioVendorChanged -[#Black]-> replicator
' _mercurioSkuChanged -[#Black]-> replicator
' _mercurioSkuRemoved -[#Black]-> replicator
' _mercurioCeOrderPaid -[#Black]-> replicator
' _mercurioCeOrderPaid -[#Black]-> replicator
' _mercurioUpdateOrdersOms -[#Black]-> replicator
' _mercurioItemPublished -[#Black]-> replicator
' _mercurioUpdatePurchaseOrder -[#Black]-> replicator
' _mercurioItemStockUpdated -[#Black]-> replicator

replicator -[#Black]---> mercurioOrdersApi
mercurioOrdersApi -[#RoyalBlue]-> mercurioDataBase

' checkout -[#DarkGrey]--> checkoutOrderPaid
' checkout -[#DarkGrey]--> checkoutOrderReinjected

checkout -[#DarkGrey]--> eventChile

' checkoutOrderPaid -[#Black]-> replicator
' checkoutOrderReinjected -[#Black]-> replicator

' OMS -[#DarkGrey]--> checkoutOrderRescheduledPublished
 OMS -[#DarkGrey]--> eventChile
' checkoutOrderRescheduledPublished -[#Black]-> replicator

' mercurioVendorLogisticUpdate -[#Black]> replicator
eventStrati -[#Black]> replicator
mercurioOrdersApi -[#RoyalBlue]> mercurioVendorLogisticUpdate

colaborator -[#Red]-> b2bWeb 
vendors -[#Red]-> b2bWeb
vendors -[#Red]-> mercurioNow
b2bWeb -[#RoyalBlue]> mercurioBff
vendorsSystems -[#Red]-> mercurioClientApi
mercurioBff -[#RoyalBlue]> mercurioAuthApi
mercurioBff -[#RoyalBlue]> mercurioOrdersApi
mercurioAuthApi -[#RoyalBlue]> retailLinkFalcon: "Vendors Authentication Flow"
mercurioAuthApi -[#RoyalBlue]> pingFed: "Walmart Colaborate Authentication Flow"
mercurioAuthApi -[#RoyalBlue]-> mercurioDataBase
mercurioClientApi -[#RoyalBlue]> mercurioAuthApi
mercurioClientApi -[#RoyalBlue]> mercurioOrdersApi

replicator -[#Black]> promiseEngine

mercurioJobsChile -[#RoyalBlue]> mercurioInventoryBase
mercurioJobsStrati  -[#RoyalBlue]-> _mercurioStockSync
mercurioJobsStrati -[#RoyalBlue]-> mercurioOrdersApi
mercurioJobsStrati -[#RoyalBlue]-> mercurioAuthApi

_mercurioStockSync -[#Black]> replicator


replicator -[#Black]-> mercurioInventoryBase
mercurioInventoryBase  -[#RoyalBlue]-> IMS
' mercurioInventoryBase -[#RoyalBlue]-> _mercurioItemStockUpdated
mercurioInventoryBase -[#RoyalBlue]-> eventChile

mercurioInventoryApi -[#RoyalBlue]-> replicator
mercurioInventoryApi -[#RoyalBlue]-> mercurioDataBase
mercurioBff -[#RoyalBlue]-> mercurioInventoryApi
mercurioInventoryApi  -[#RoyalBlue]-> mercurioItemLeadtimeUpdated

mercurioItemLeadtimeUpdated -[#Black]> replicator



@enduml