@startuml
!include <cloudinsight/mongodb>
!include <cloudinsight/kafka>
title B2B - Architecture AsIs
left to right direction
actor users
rectangle public {
    rectangle "b2b-web" as b2bWeb
    rectangle "mercurio-client-api" as mercurioClientApi
    rectangle "mercurio-now" as mercurioNow
    rectangle "mercurio-bff" as mercurioBff
}

rectangle privacy {
    rectangle "b2b-Api" as b2bApi #red;line:white;line.bold;text:white
    rectangle "mercurio-unleash" as mercurioUnleash
    cloud gcp #red;line:white;line.bold;text:white
    database "<$mongodb>" as mongodb #green;line:white;line.bold;text:white
    rectangle "mercurio-inventory-api" as mercurioInventoryApi
    queue "<$kafka>" as kafka #black;line:white;line.bold;text:white
    rectangle "mercurio-orders-api" as mercurioOrdersApi
}


users --> b2bWeb
users --> mercurioClientApi
users --> mercurioNow
b2bWeb --> mercurioBff
mercurioBff --> b2bApi
b2bApi --> mercurioUnleash
mercurioUnleash --> gcp: Unleash Authentication
mercurioUnleash --> mongodb: unleash
mercurioBff --> mercurioInventoryApi
mercurioBff --> mercurioOrdersApi
mercurioInventoryApi --> mongodb: inventory
mercurioInventoryApi --> kafka
' mercurioClientApi --> mercurioInventoryApi
' mercurioClientApi --> mercurioOrdersApi
@enduml