@startuml
    left to right direction
    !include <cloudinsight/mongodb>
    !include <cloudinsight/kafka>
    title Sync Stock with IMS Broker - Pre-Strati - (ETLLess)

    rectangle Chile {
        rectangle mercurio {
            rectangle "mercurio-jobs" as mercurioJobs
            queue "<$kafka> _mercurio-stock-sync-cl-east" as mercurioStockSync #black;line:white;line.bold;text:white
            rectangle "mercurio-inventory-base" as mercurioInventoryBase
            database "<$mongodb>" as inventoryDb #green;line:white;line.bold;text:white
            queue "<$kafka> _mercurio-item-stock-updated-cl-[east|west]" as mercurioItemStock #black;line:white;line.bold;text:white

        }

        rectangle ims {
            rectangle broker
        }
    }

    queue "<$kafka> replicator" as replicator #black;line:white;line.bold;text:white

    rectangle Strati {
        rectangle mercurio as mercurioStrati {
            rectangle "mercurio-inventory-api" as mercurioInventoryApi
                    database "<$mongodb>" as inventoryDbStrati #green;line:white;line.bold;text:white
        }
    }


    mercurioJobs -[#black]> mercurioStockSync
    mercurioStockSync -[#black]> mercurioInventoryBase: (1) Trigger Syncronization
    mercurioInventoryBase -[#green]> inventoryDb: (2) Get last sync date
    inventoryDb -> mercurioInventoryBase #green
    mercurioInventoryBase -> inventoryDb #green
    mercurioInventoryBase -> broker : (3) Get Updated Stock
    broker --> mercurioInventoryBase 
    mercurioInventoryBase -> mercurioItemStock #black
    mercurioItemStock --> replicator #black
    replicator --> mercurioItemStock #black
    replicator --> mercurioInventoryApi #black : (4) Stock Updated
    mercurioInventoryApi -> inventoryDbStrati #green
    inventoryDbStrati -> mercurioInventoryApi #green

@enduml