@startuml
actor fixer
"mercurio-bff" -> "mercurio-orders-api" : 1.1: GET: /v2/orders
"mercurio-orders-api" -> "mercurio-orders-base" : 1.2: GET: /v1/orders for data grid result + mongoDB
note right: Make a merge orders on B2B with orders in OMS
"mercurio-bff" -> "mercurio-orders-api" : 2.1: GET: /v2/orders/host
oms <- "mercurio-orders-base" : 1.3: Get orders from OMS DataBase
"mercurio-orders-api" -> "mercurio-orders-base": 2.2: GET: /v1/orders for generate host file + mongoDB
note right: Make a merge orders on b2b with orders in OMS
oms <- "mercurio-orders-base" : 2.3: Get orders from OMS DataBase
fixer -> "mercurio-bff" : 3.1: Execute manual order fix
"mercurio-bff" -> "mercurio-orders-base" : 3.2: GET: /v1/orders/shipping-groups/${shippingGroupId}/fix
oms <- "mercurio-orders-base" : 3.3: Get orders from OMS DataBase
"mercurio-orders-base" -> "mercurio-orders-api" : 3.4: POST: /v2/orders/upsert-many-from-oms
note right: Save and/or update orders in B2B
@enduml